[tool.ruff]
line-length = 100
target-version = "py311"
select = ["F", "E", "W", "I"]
ignore = ["E501"]
fix = true

[tool.ruff.isort]
known-first-party = ["app"]
force-single-line = false
combine-as-imports = true

[tool.ruff.per-file-ignores]
# Allow some flexibility in tests
"tests/*" = ["E402"]
